### ISSUE TITLE
Bug:  Raid won't clear at end of day

### ISSUE THREAD

**Issue by Rebelpilot** [alanschapira/RaidBot#5]
If the raid was created at the end of the day and it's shorter than the clear timer, then the raid won't clear properly.

**Comment by Rebelpilot** [comment]
Looking up how to code, but could make sure the clear timer is independent of NTP time OR at 23:59 Local time, clear all raids is automatically run.

**Comment by alanschapira** [comment]
This will be fixed with this issue: https://github.com/alanschapira/RaidBot/issues/12
